/* ============================================================
   AI Feedback — student view of the trained reviewer's work
   ------------------------------------------------------------
   After submitting a challenge, the playground calls
   AiFeedback.show(challengeId). It fetches the student's latest
   AI review from /api/ai-reviews/mine/:challengeId and renders
   a compact card:
     • verdict + score + quality band
     • concepts the code used (from the trained model)
     • 2 strengths / 2 improvements (never a wall of text)
   The review is generated by the LOCAL engine (no LLM) and only
   affects the student's record after an admin approves it — the
   card is informational and says so.
   ============================================================ */

const AiFeedback = (() => {
  const esc = s => String(s == null ? '' : s)
    .replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));

  /* Colors per verdict band */
  const BANDS = {
    pass:       { color: '#059669', bg: '#ecfdf5', border: '#a7f3d0', label: 'Passed' },
    fail:       { color: '#dc2626', bg: '#fef2f2', border: '#fecaca', label: 'Not passed' },
    needs_review: { color: '#b45309', bg: '#fffbeb', border: '#fde68a', label: 'Needs review' },
  };

  /* One card element injected above the output panel */
  function cardHtml(review) {
    if (!review || !review.review) return '';
    const r = review.review || {};
    const band = BANDS[review.verdict] || BANDS.needs_review;
    const quality = review.quality || 'beginner';
    const score = typeof review.score === 'number' ? review.score : 0;

    const concepts = (r.detectedConcepts || []).slice(0, 4)
      .map(c => `<span style="display:inline-block;padding:2px 8px;border-radius:999px;background:${band.bg};color:${band.color};font-size:11px;font-weight:600;margin:2px 4px 2px 0;border:1px solid ${band.border};">${esc(c.concept)} ${Math.round((c.strength || 0) * 100)}%</span>`)
      .join('');

    const strengths = (r.strengths || []).slice(0, 2)
      .map(s => `<div style="font-size:12px;color:#065f46;margin:3px 0;">✓ ${esc(s)}</div>`).join('');
    const improvements = (r.improvements || []).slice(0, 2)
      .map(s => `<div style="font-size:12px;color:#92400e;margin:3px 0;">▲ ${esc(s)}</div>`).join('');

    return `
    <div id="ai-feedback-card" style="margin:10px 0;padding:12px 14px;border:1px solid ${band.border};border-radius:8px;background:${band.bg};">
      <div style="display:flex;align-items:center;gap:8px;flex-wrap:wrap;margin-bottom:6px;">
        <strong style="font-size:12.5px;color:${band.color};">AI Code Review</strong>
        <span style="font-size:11.5px;color:${band.color};background:#fff;border:1px solid ${band.border};padding:1px 8px;border-radius:999px;">${band.label} · ${score}/100 · ${esc(quality)}</span>
        <span style="margin-left:auto;font-size:10.5px;color:#6b7280;">local engine · no external AI</span>
      </div>
      ${concepts ? `<div style="margin-bottom:6px;">${concepts}</div>` : ''}
      ${strengths}
      ${improvements}
      <div style="font-size:10.5px;color:#6b7280;margin-top:6px;">Informational only — your official result and coins are applied after an admin confirms the AI's marking.</div>
      <div style="margin-top:8px;">
        <button onclick="this.closest('#ai-feedback-card').remove()" style="background:none;border:none;color:#6b7280;font-size:11px;cursor:pointer;padding:0;">Dismiss</button>
      </div>
    </div>`;
  }

  /**
   * Fetch and show the AI review for a challenge.
   * Safe to call always — silently does nothing when not logged in,
   * no review exists, or the endpoint is unavailable.
   */
  async function show(challengeId, mountSelector) {
    try {
      const mount = document.querySelector(mountSelector || '#challenge-output');
      if (!mount) return;
      const res = await fetch(`/api/ai-reviews/mine/${challengeId}`, {
        headers: { Authorization: `Bearer ${(await supabaseClient.auth.getSession()).data.session?.access_token}` },
      });
      if (!res.ok) return;
      const json = await res.json();
      if (!json.review) return;
      // Remove any previous card first
      document.getElementById('ai-feedback-card')?.remove();
      mount.insertAdjacentHTML('beforebegin', cardHtml(json.review));
    } catch {
      /* feedback is best-effort — never break the submission flow */
    }
  }

  return { show, cardHtml };
})();

if (typeof module !== 'undefined' && module.exports) module.exports = { AiFeedback };
