#!/usr/bin/env node
/* ============================================================
   fix_challenge_hints.js
   ============================================================
   Replaces the generic filler hints on every active challenge
   with challenge-specific, progressive hints generated from the
   challenge's own data (title, description, starter code, tests).

   Modes:
     node fix_challenge_hints.js            → writes migrations/fix_challenge_hints.sql
     node fix_challenge_hints.js --apply    → updates Supabase directly
                                              (requires valid API keys in .env)
     node fix_challenge_hints.js --dry-run  → prints a preview table, no writes

   Safe by design:
   - Only touches challenges whose hints are the generic filler
     (or empty), unless --force is given.
   - Deterministic output; re-runnable SQL.
   ============================================================ */

require('dotenv').config();

const fs = require('fs');
const path = require('path');
const { generateHints, normalizeType } = require('./backend/services/hintGenerator');

const APPLY = process.argv.includes('--apply');
const DRY = process.argv.includes('--dry-run');
const FORCE = process.argv.includes('--force');

/* The exact filler strings seeded by migrations/add_challenge_hints.sql */
const FILLER = [
  'Re-read the task carefully and identify exactly what output or behavior is expected.',
  'Break the problem into small steps and solve one step at a time.',
  'Check your syntax: variable names, brackets, and quotes must match exactly.'
];

function isFiller(hints) {
  if (!Array.isArray(hints) || hints.length === 0) return true; // empty = fix
  if (hints.length !== FILLER.length) return false;
  return hints.every((h, i) => String(h).trim() === FILLER[i]);
}

/** Escape a string for a SQL dollar-quoted literal */
function dollarQuote(s, tag) {
  if (s.includes(`$${tag}`)) throw new Error('dollar-tag collision');
  return `$${tag}$${s}$${tag}$`;
}

async function fetchChallenges() {
  const { adminClient } = require('./backend/config/database');
  const { data, error } = await adminClient
    .from('challenges')
    .select('id, title, description, difficulty, challenge_type, language, starter_code, starter_html, expected_output, test_cases, hints')
    .eq('is_active', true)
    .order('course_id')
    .order('sort_order');
  if (error) throw error;
  return data || [];
}

function previewRow(ch, hints) {
  return {
    id: ch.id,
    type: normalizeType(ch),
    title: (ch.title || '').slice(0, 48),
    action: isFiller(ch.hints) ? 'REPLACE' : (FORCE ? 'FORCE' : 'SKIP'),
    hint1: (hints[0] || '').slice(0, 70) + '…'
  };
}

async function main() {
  const challenges = await fetchChallenges();
  console.log(`Fetched ${challenges.length} active challenges.\n`);

  const updates = [];
  let skipped = 0;

  for (const ch of challenges) {
    const hints = generateHints(ch);
    const row = previewRow(ch, hints);
    if (row.action === 'SKIP') { skipped++; continue; }
    updates.push({ ch, hints });
    if (DRY) console.log(`[${row.action}] (${row.type}) ${row.title}\n          → ${row.hint1}`);
  }

  console.log(`\n${updates.length} to update, ${skipped} skipped (custom hints preserved).`);

  if (DRY || updates.length === 0) return;

  if (APPLY) {
    const { adminClient } = require('./backend/config/database');
    let done = 0;
    for (const { ch, hints } of updates) {
      const { error } = await adminClient
        .from('challenges')
        .update({ hints: JSON.stringify(hints) })
        .eq('id', ch.id);
      if (error) { console.error(`✗ ${ch.title}: ${error.message}`); process.exit(1); }
      done++;
      if (done % 25 === 0) console.log(`  … ${done}/${updates.length}`);
    }
    console.log(`\n✅ Applied challenge-specific hints to ${done} challenges.`);
    return;
  }

  /* ── Emit SQL ── */
  const blocks = updates.map(({ ch, hints }) => {
    const tag = 'h' + String(ch.id).replace(/-/g, '');
    const arr = `jsonb_build_array(\n${hints.map(h => `    ${dollarQuote(h, tag)}`).join(',\n')}\n  )`;
    return `-- ${(ch.title || '').replace(/--/g, '—')} (${normalizeType(ch)})\nUPDATE public.challenges SET hints = ${arr} WHERE id = '${ch.id}';`;
  });

  const sql = `-- ============================================================
-- FIX CHALLENGE HINTS — auto-generated; do not edit by hand.
-- Generated by: node fix_challenge_hints.js
-- Generated at: ${new Date().toISOString()}
--
-- Replaces the generic filler hints (seeded by
-- migrations/add_challenge_hints.sql) with challenge-specific,
-- progressive hints derived from each challenge's own data:
--   hint 1 re-orients to the core concept,
--   hint 2 names the technique and the concrete objects involved,
--   hint 3 gives a type-aware concrete next action.
--
-- Challenges whose hints are NOT the standard filler (i.e. were
-- hand-authored) are left untouched.
-- RE-RUNNABLE. Run in the Supabase SQL Editor.
-- ============================================================

${blocks.join('\n\n')}

-- ============================================================
-- VERIFICATION
-- ============================================================
SELECT
  count(*)                                                        AS active_challenges,
  count(*) FILTER (WHERE jsonb_array_length(hints) = 3)           AS with_three_hints,
  count(*) FILTER (WHERE hints @> '[{"omitted":null}]'::jsonb)    AS bad_shape,
  count(*) FILTER (
    WHERE hints ->> 0 LIKE 'Re-read the task carefully%'
  )                                                               AS still_filler
FROM public.challenges WHERE is_active = true;
`;

  const outPath = path.join(__dirname, 'migrations', 'fix_challenge_hints.sql');
  fs.writeFileSync(outPath, sql);
  console.log(`\nWrote ${outPath} (${(sql.length / 1024).toFixed(0)} KB, ${updates.length} UPDATE statements)`);
  console.log('Run it in the Supabase SQL Editor (or re-run this script with --apply).');
}

main().catch(err => {
  console.error('Failed:', err.message);
  process.exit(1);
});
